### ISSUE TITLE
Excessive consumption of disk

### ISSUE THREAD

**Issue by echer** [Karm/mod_cluster-dockerhub#4]
I use your container httpd apache with modcluster in production, and I'm having a problem, the space used by the container grows exponentially, this happens only with modcluster container, others do not use this quantidde disk space. Has anyone ever experienced this? Can you tell me what might be causing this excessive consumption of disk in the container ?, I need to restart the server every time this happens it gets to the point of halting and docker can not finish the container.

The log server is only this

`Starting httpd with mod_cluster
===============================
MODCLUSTER_PORT            80
MODCLUSTER_ADVERTISE       Off
MODCLUSTER_ADVERTISE_GROUP 224.0.1.105:23364
MODCLUSTER_NET             192. 172. 10. 179. 213.
MODCLUSTER_MANAGER_NET     192. 172. 10. 179. 213.

Creating /opt/httpd-build/conf/extra/mod_cluster.conf configuration file:

LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so
LoadModule manager_module modules/mod_manager.so
LoadModule advertise_module modules/mod_advertise.so

MemManagerFile /opt/httpd-build/cache/mod_cluster

<IfModule manager_module>
Listen 80
  <VirtualHost *:80>
    <Directory />
      Require ip 192. 172. 10. 179. 213.
    </Directory>
    ServerAdvertise Off
    AdvertiseGroup 224.0.1.105:23364
    EnableMCPMReceive
    <Location /mcm>
      SetHandler mod_cluster-manager
      Require ip 192. 172. 10. 179. 213.
   </Location>
  </VirtualHost>
</IfModule>

-- /opt/httpd-build/bin/apachectl start -DFOREGROUND`

**Comment by Karm** [comment]
@echer Lemme take a look...

**Comment by echer** [comment]
I believe to be related to docker, something it causes excessive consumption of disk.
